### ISSUE TITLE
Can't download a midi file

### ISSUE THREAD

**Issue by przem360** [edwardhorsey/euclidean-rhythm#13]
It seems to be impossible to download MIDI file.

The page `https://euclidean-ryhthm.web.app/` loads and seems to work as expected. After loading the page, console outputs following message:

```
WebAudio.jsx:6 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
(anonymous)	@	WebAudio.jsx:6
```

I can create, edit and play rhythms but clicking `generate MIDI file` button does nothing.

This problem occurs in Firefox and in Chrome on Linux Mint. OS is up to date, so are browsers.

**Comment by edwardhorsey** [comment]
Hey @przem360, thanks for flagging this. I've rebuilt with the correct api endpoint in place. 

Cheers 🙌

**Comment by przem360** [comment]
Yes! Now it works.
Thank you :)
Closing.
